restaurants = [
  "Burger King",
  "Domino’s",
  "Manchu Wok",
  "Papa John’s",
  "Pizza Hut",
  "Subway",
  "Wendy’s",
  "Dairy Queen",
  "KFC",
  "Starbucks",
  "Denny’s",
  "Popeyes",
  "Johnny Rockets",
  "Little Caesars Pizza",
  "Chester’s Chicken",
  "Cinnabon",
  "McDonald’s",
  "Mucho Burrito",
  "Tim Horton’s",
  "Fatburger",
  "The Old Spaghetti Factory",
  "The Keg Steakhouse",
  "7-11",
  "A&W Restaurants",
  "Earls",
  "Panago Pizza",
  "Original Joes’s",
  "Pagliacci Pizza",
  "White Spot Restaurants",
  "De Dutch Pannekoek House",
  "Red Robin",
  "Boston Pizza",
  "Orange Julius",
  "Thai Express",
  "New York Fries",
  "Booster Juice",
  "Swiss Chalet",
  "Edo Japan",
  "Costco Food Court",
  "Cinnzeo",
  "A&W (Canada)",
  "Browns Socialhouse",
  "Bento Sushi",
  "Montana’s BBQ",
  "Cora",
  "McDonald’s Canada",
];

restaurants = list(set(restaurants));
restaurants.sort();
